//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapunovProjectDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int IdStaff { get; set; }
        public string NameStaff { get; set; }
        public int IdGenderStaff { get; set; }
        public int IdEducationStaff { get; set; }
        public System.DateTime DateOfBirthStaff { get; set; }
        public string AdressStaff { get; set; }
        public string PhoneNumberStaff { get; set; }
        public string EmailStaff { get; set; }
        public int IdPositionAtWork { get; set; }
        public decimal SalaryStaff { get; set; }
        public System.DateTime HireDateStaff { get; set; }
        public int IdUser { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual GenderStaff GenderStaff { get; set; }
        public virtual PositionAtWork PositionAtWork { get; set; }
        public virtual User User { get; set; }
    }
}
